name: fontsource_example
description: Fontsource example project.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  fontsource:
    path: ../
  fontsource_gen:
    path: .fontsource

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

fontsource:
  fonts:
    alex-brush:
      subsets: all
      weights: [400]
      styles: [normal]
