name: fontsource
description: Easily add Fontsource fonts to your flutter app. Includes a dart interface for the Fontsource API.
version: 0.4.0
repository: https://github.com/fontsource/fontsource-flutter

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  json2yaml: ^3.0.0
  path: ^1.8.0
  progress_bar: ^1.0.0
  version: ^3.0.0
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

executables:
  fontsource:
