name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'
          channel: 'stable'

      - run: dart pub get

      - run: dart run .scripts/publish.dart '${{ secrets.PUB_CREDENTIALS }}' ${{ secrets.GITHUB_TOKEN }}
